// <auto-generated />
namespace eProcurement_PAUP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class orderedquantity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderedquantity));
        
        string IMigrationMetadata.Id
        {
            get { return "202405131549085_ordered-quantity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
